apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "echo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "echo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echo-app.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTHOR
              value: {{ .Values.environment.author | quote }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}